### ISSUE TITLE
Why the zip in the link given in the repo connot unzip right?

### ISSUE THREAD

**Issue by zmh02** [ASSERT-KTH/VRepair#11]
Firstly, we try use the zip -s0 to get all zip in one, but it no useful. Then, We try use zip -F but still connot unzip right.

**Comment by network-trash** [comment]
这个压缩文件能在Linux系统上解压吗

**Comment by SteveKommrusch** [comment]
I was able to download and unzip the file on my Linux system (Macbook) using 'unzip VRepair-main.zip'. Note that the file is 7GB so you need to wait for the full download to complete.

Normally, I use git commands for repositories. You may need to set up the 'git' command on your system, then run:
  git clone git@github.com:SteveKommrusch/VRepair.git

**Comment by network-trash** [comment]
Sorry, maybe I didn't express clearly. My problem is that the link you gave, that is, the zip file corresponding to the model you trained, cannot be decompressed normally.

**Comment by network-trash** [comment]
such as this, https://kth-my.sharepoint.com/:u:/g/personal/zimin_ug_kth_se/Edn05UsQUmpDrGZNJK6GmuIBPdIFp4_llmFuU7RegWYhCw?e=u5Y35p

**Comment by SteveKommrusch** [comment]
Hmm. That is different than the main github link, but it still worked for
me on Linux (MACOS) simply using 'unzip'. Note that the file is huge - over
22GB.

Steve

**Comment by monperrus** [comment]
The model is a split zip file.

You first have to reconstruct the zip file and then unzip.

```
zip -F all_VRepair_models_parts.zip --out vrepair.zip
unzip vrepair.zip
```
