### ISSUE TITLE
Expired Link

### ISSUE THREAD

**Issue by kakairesteven** [ASSERT-KTH/VRepair#15]
Hello there. I wish to get an active link to the models. The links shared are expired. Thanks.

**Comment by chenzimin** [comment]
Thanks for reminding me, I am trying to upload it Zenodo for as a more permanent solution.

**Comment by monperrus** [comment]
deuplicate of #16 

@kakairesteven we have uploaded the models on Zenodo, see README

**Comment by kakairesteven** [comment]
Much appreciated.
