### ISSUE TITLE
The sharepoints links shared are expired

### ISSUE THREAD

**Issue by 17chase** [ASSERT-KTH/VRepair#16]
Hi~I wish to get an active link to the models. The links shared are expired. Thanks.

**Comment by chenzimin** [comment]
Thanks for reminding me, I am trying to upload it Zenodo as a more permanent solution.

**Comment by monperrus** [comment]
@17chase we're working on it

**Comment by SteveKommrusch** [comment]
This is just an update. We are working to find a better location for the
models. At the moment you can find some at the links below. We'll update
the main page with the correct links once we have them confirmed.

> z01 https://zenodo.org/records/10445594
> z02 https://zenodo.org/records/10448514
> z03 https://zenodo.org/records/10693640

Regards,
Steve

**Comment by monperrus** [comment]
@17chase  README updated with all Zenodo links.

**Comment by 17chase** [comment]
> README 更新了所有 Zenodo 链接。

thanks~
