### ISSUE TITLE
Hardwares used for experiments

### ISSUE THREAD

**Issue by dangnguyenngochai** [ASSERT-KTH/VRepair#6]
Can you share the hardware specifications used for experiments, along with the time it takes for transfer learning in rq2 and pre-training + target domain training in rq3 ?

**Comment by chenzimin** [comment]
We used NVIDIA Tesla T4 to train all the models.

> transfer learning in rq2

source domain training (training on a bug fix corpus) takes ~3 - 7 days, target domain training (truing on a vulnerability fix corpus) takes ~1h.

> pre-training + target domain training in rq3 

pre-training take ~3-7 days, and target domain training takes similar time as before.

**Comment by dangnguyenngochai** [comment]
How about your other method, SeqTrans, how long does it take for training using the specifications mentioned in your paper "Intel Xeon E5 processor, four Nvidia 3090 GPU, and 1TB RAM"

**Comment by monperrus** [comment]
> How about your other method, SeqTrans

We're not authors of SeqTrans.

**Comment by dangnguyenngochai** [comment]
Very sorry, my mistake.

**Comment by chenzimin** [comment]
I am now contacting Zenodo to host all the models (compressed version is 273GB).

I have them currently uploaded to OneDrive for now:
* https://kth-my.sharepoint.com/:u:/g/personal/zimin_ug_kth_se/EV9uVzTRIF5HlMrRNHPHjfoBOivr63Is023EFzNe1Ax9zg?e=dEck8z
* https://kth-my.sharepoint.com/:u:/g/personal/zimin_ug_kth_se/EVy6M7UZ0rVPr3c28wxKH2cBYZPKGSPqb5_lqLOrduzvlQ?e=lgn8TV
* https://kth-my.sharepoint.com/:u:/g/personal/zimin_ug_kth_se/EVTHzJRcIW9Ak5PVn38RYX8BEWH5zyKlSlJh9KgKXU3SYw?e=WgSkHp
* https://kth-my.sharepoint.com/:u:/g/personal/zimin_ug_kth_se/ESU_mesDK3lPq2aF4kve2_4BwM41wyFarIOe9E8JpD2dLw?e=jpJeZl
* https://kth-my.sharepoint.com/:u:/g/personal/zimin_ug_kth_se/ESEhDRyeJ9pGtB7kEqjEfYUBPL19rR3g7ASYuUUqb5y-LQ?e=mu2umn
* https://kth-my.sharepoint.com/:u:/g/personal/zimin_ug_kth_se/Edn05UsQUmpDrGZNJK6GmuIBPdIFp4_llmFuU7RegWYhCw?e=u5Y35p

I will update the repo about the model directory structure.

**Comment by chenzimin** [comment]
The link will be valid until Sep 2022. The models can be stored at OneDrive at least until Oct 2023, in the meantime I will try to find a location to host the models.

**Comment by kakairesteven** [comment]
Greetingas @chenzimin, much thanks for the research work. I wish to have a downloadable copy of the model. Thanks.

**Comment by monperrus** [comment]
The models have been pushed to Zenodo, see README.
