### ISSUE TITLE
special token handling

### ISSUE THREAD

**Issue by oathaha** [ASSERT-KTH/VRepair#7]
In the paper you said that 2 special tokens <StartLoc> and <EndLoc> are added in input lines (vulnerable lines). Can you tell me whether these tokens are differently treated or they are treated as normal tokens?

For example, if a model identifies <StartLoc> and <EndLoc> tokens, the model will do something different from what it does to normal token.

**Comment by nashid** [comment]
@oathaha, after reading the paper, I see that tokens are added as part of the input. The model does not treat any differently.

**Comment by SteveKommrusch** [comment]
Correct, the special tokens identifying the 1st buggy line are added before
feeding the input to VRepair (such as by identifying risky lines using a
tool like Infer). Beyond that, VRepair learns based on training examples
that these tokens identify the 1st buggy line and it learns to make the
first proposed modification within this line. No further special processing
needs to be done. VRepair may learn that further lines must be modified
based on training experience.

Regards,
Steve
